version: "3"

services:
  redis:
    image: redis:3.0.5
    restart: always
    ports:
      - "6379:6379"

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: isucon5q
      MYSQL_DATABASE: isucon5q  # Inherit from ISUCON5_DB_NAME
    ports:
      - "63306:3306"
    volumes:
      - ./data:/var/lib/mysql

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile-golang
    restart: always
    links:
      - db
      - redis
    external_links:
      - db:db
      - redis:redis
    environment:
      - ISUCON5_DB_PASSWORD=isucon5q
      - ISUCON5_DB_HOST=db
      - ISUCON5_DB_USE_TCP=1
      - ISUCON5_REDIS_USE_TCP=1
      - ISUCON5_REDIS_HOST=redis
      - ISUCON5_REDIS_LOAD_AOF=0
    ports:
      - "8080:8080"
